FROM golang:1.19-alpine

WORKDIR /app

COPY go.* ./


RUN go mod download

RUN apk update && \
    apk add openjdk11

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk

ENV PATH="$JAVA_HOME/bin:$PATH"

COPY . .

RUN go build -o main main.go


EXPOSE 8800

CMD ["./main"]
