FROM golang:1.19-alpine as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .

RUN go build -o main main.go

FROM alpine:3.17

RUN apk add --no-cache openjdk11 ca-certificates
RUN apk add --no-cache gcc musl-dev g++

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 8800

CMD ["./main"]
